# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(BuildFile(src/python/verst/pants/s3cache/BUILD, FileSystemProjectTree(/Users/todd/git/pants-plugins)), s3cache_packaged))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: MIT License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python',
                       'Topic :: Software Development :: Build Tools'],
    'description': 'Play plugin for pants',
    'entry_points': {   'pantsbuild.plugin': [   'build_file_aliases = play.register:build_file_aliases',
                                                 'register_goals = play.register:register_goals',
                                                 'global_subsystems = play.register:global_subsystems']},
    'install_requires': [   'boto3==1.4.4',
                            'pantsbuild.pants>=1.1.0',
                            'pyjavaproperties==0.6',
                            'six>=1.9.0,<2'],
    'license': 'MIT',
    'long_description': 'Play plugin for pants',
    'maintainer': 'Nadav Sr. Samet, Alex Moore, Nitay Joffe',
    'maintainer_email': 'alex@actioniq.com',
    'name': 'com.actioniq.playpants',
    'namespace_packages': ['play', 'play/targets', 'play/tasks'],
    'package_data': {   },
    'package_dir': {   '': 'src/python'},
    'packages': ['play'],
    'url': 'https://github.com/ActionIQ/play-pants',
    'version': '0.2.1',
    'zip_safe': True}
)
