java_library(
    name = 'playpants-runner',
    sources = ['*.scala'],
    dependencies = [
        '3rdparty/jvm:play',
        '3rdparty/jvm:scopt'],
    provides = artifact(org='com.thesamet', name='play-pants-runner', repo=public,
                        publication_metadata=publication_metadata('Runs Play'))
    )

