python_library(
  name = 'play_packaged',
  sources = rglobs('*.py'),
  dependencies = [
  ],
  provides = setup_py(
    name = 'play',
    version = '0.2.1',
    description = 'Play plugin for Pants',
    url = 'https://github.com/ActionIQ/play-pants',
    author = 'Nadav Sr. Samet, Alex Moore, Nitay Joffe',
    author_email = 'alex@actioniq.com',
    license = 'Apache License, Version 2.0',
    zip_safe = True,
    classifiers = [
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
    ]
  )
)
