python_library(
  name = 'plugin',
  sources = rglobs('*.py'),
  dependencies = [
  ],
  provides = setup_py(
    name = 'thesamet.playpants',
    version = '0.1.2',
    description = 'Play plugin for Pants',
    url = 'https://github.com/thesamet/playpants',
    author = 'Nadav Sr. Samet',
    author_email = 'nadav@thesamet.com',
    license = 'Apache License, Version 2.0',
    zip_safe = True,
    classifiers = [
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
    ]
  )
)
