java_library(
    name = 'play-pants-tool',
    sources = rglobs('*.scala'),
    dependencies = [
        '3rdparty/jvm:twirl-compiler', 
        '3rdparty/jvm:routes-compiler', 
        '3rdparty/jvm:scopt'],
    provides = artifact(org='com.thesamet', name='play-pants-tool', repo=public,)
    )
